// Reference copy of the 2026 London kit inventory (source of truth is Supabase).
// Items with qty > 1 appear as separate rows with unit_number 1, 2, 3 … in the DB.

export const DEFAULT_INVENTORY = [
  // ── Cameras ───────────────────────────────────────────────────────────────
  { category: 'Cameras', name: 'RED Komodo-X',   qty: 2 },
  { category: 'Cameras', name: 'Sony A7SIII',    qty: 1 },
  { category: 'Cameras', name: 'Sony FX3',        qty: 1 },

  // ── Lenses ────────────────────────────────────────────────────────────────
  { category: 'Lenses', name: 'Laowa Ranger 50-130mm Z',  qty: 1 },
  { category: 'Lenses', name: 'Laowa Ranger 14-50mm Z',   qty: 1 },
  { category: 'Lenses', name: 'Sigma 18-35mm EF',         qty: 1 },
  { category: 'Lenses', name: 'Laowa Probe Lens EF',      qty: 1 },
  { category: 'Lenses', name: 'Samyang Fisheye EF',       qty: 1 },
  { category: 'Lenses', name: 'Sigma 30mm MFT',           qty: 1 },
  { category: 'Lenses', name: 'Sigma 70-200mm E',         qty: 1 },
  { category: 'Lenses', name: 'Sigma 24-70mm E',          qty: 3 },
  { category: 'Lenses', name: 'Tamron 70-180mm E',        qty: 1 },
  { category: 'Lenses', name: 'Laowa Macro 60mm E',       qty: 1 },

  // ── Adapters ──────────────────────────────────────────────────────────────
  { category: 'Adapters', name: 'Metabones EF-E Mount T',   qty: 1 },
  { category: 'Adapters', name: 'Metabones EF-MFT Mount T', qty: 1 },
  { category: 'Adapters', name: 'Megadap EF-Z',              qty: 1 },
  { category: 'Adapters', name: 'Megadap E-Z',               qty: 1 },
  { category: 'Adapters', name: 'Sigma MC-11 EF-E',          qty: 1 },
  { category: 'Adapters', name: 'URTH EF-X',                 qty: 1 },
  { category: 'Adapters', name: 'Neewer Step Up Rings Set',  qty: 1 },

  // ── Filters ───────────────────────────────────────────────────────────────
  { category: 'Filters', name: 'Tide Variable ND 77mm',          qty: 1 },
  { category: 'Filters', name: 'Tiffen Variable ND 77mm',        qty: 1 },
  { category: 'Filters', name: 'Tiffen Variable ND 82mm',        qty: 5 },
  { category: 'Filters', name: 'Gobe CPL 77mm',                  qty: 1 },
  { category: 'Filters', name: 'Gobe Variable ND 82mm',          qty: 1 },
  { category: 'Filters', name: 'Fotonic Kaleidoscope 77mm',      qty: 1 },
  { category: 'Filters', name: 'PrismFX Split Diopter 82mm',    qty: 1 },
  { category: 'Filters', name: 'URTH Star Filters 4,6,8 77mm',  qty: 1 },
  { category: 'Filters', name: 'Tiffen Circular Polarizer 82mm', qty: 1 },
  { category: 'Filters', name: 'Tiffen Black Pro Mist 82mm 1/8', qty: 2 },

  // ── Action Cameras ────────────────────────────────────────────────────────
  { category: 'Action Cameras', name: 'Insta360 X5',       qty: 1 },
  { category: 'Action Cameras', name: 'Osmo Action 4',     qty: 2 },
  { category: 'Action Cameras', name: 'Osmo Action 5 Pro', qty: 4 },

  // ── Monitoring ────────────────────────────────────────────────────────────
  { category: 'Monitoring', name: 'DJI Transmission Combo',       qty: 1 },
  { category: 'Monitoring', name: 'Atomos Ninja V Black',         qty: 1 },
  { category: 'Monitoring', name: 'Atomos Ninja V Gold',          qty: 4 },
  { category: 'Monitoring', name: 'Atomos Shinobi 7',             qty: 1 },
  { category: 'Monitoring', name: 'Angelbird AtomX SSDmini 500GB',qty: 1 },
  { category: 'Monitoring', name: 'Angelbird AtomX SSDmini 1TB',  qty: 1 },
  { category: 'Monitoring', name: 'Smallrig HDMI Cable',          qty: 4 },
  { category: 'Monitoring', name: 'SDI Cable',                    qty: 2 },
  { category: 'Monitoring', name: 'DJI SDR',                      qty: 8 },
  { category: 'Monitoring', name: 'Eliminator',                   qty: 8 },
  { category: 'Monitoring', name: 'D-Tap Cable',                  qty: 6 },
  { category: 'Monitoring', name: 'TV Monitor',                   qty: 1 },

  // ── Audio ─────────────────────────────────────────────────────────────────
  { category: 'Audio', name: 'Zoom H6',                      qty: 1 },
  { category: 'Audio', name: 'Zoom H8',                      qty: 1 },
  { category: 'Audio', name: 'Zoom F8N',                     qty: 1 },
  { category: 'Audio', name: 'Rode NTG-II',                  qty: 4 },
  { category: 'Audio', name: 'Sennheiser EW G4',             qty: 1 },
  { category: 'Audio', name: 'Rode Video Mic Pro',           qty: 1 },
  { category: 'Audio', name: 'Se Electronics Condenser Set', qty: 1 },
  { category: 'Audio', name: 'Rode Lavelier II',             qty: 2 },
  { category: 'Audio', name: 'Sennheiser ME 2',              qty: 1 },
  { category: 'Audio', name: 'DJI Mic 2',                    qty: 3 },
  { category: 'Audio', name: 'Boom Pole',                    qty: 1 },
  { category: 'Audio', name: 'XLR Cable 10m',                qty: 1 },
  { category: 'Audio', name: 'XLR Cable 6m',                 qty: 4 },
  { category: 'Audio', name: 'XLR Cable 1m',                 qty: 1 },
  { category: 'Audio', name: 'XLR to 3.5mm Cable 0.5m',     qty: 1 },
  { category: 'Audio', name: 'TRS Cable 3m',                 qty: 2 },
  { category: 'Audio', name: 'TRS Cable 1.5m Stretchy',      qty: 1 },
  { category: 'Audio', name: 'Sennheiser SEN-508664',         qty: 1 },
  { category: 'Audio', name: 'Rycote Dead Cat',               qty: 2 },
  { category: 'Audio', name: 'Rycote Lav Muff',               qty: 1 },
  { category: 'Audio', name: 'Sound Blankets',                qty: 4 },
  { category: 'Audio', name: 'Rycote Stickies',               qty: 1 },

  // ── Lighting ──────────────────────────────────────────────────────────────
  { category: 'Lighting', name: 'Aputure 1200D',                   qty: 1 },
  { category: 'Lighting', name: 'Aputure LS 600C Pro II',          qty: 1 },
  { category: 'Lighting', name: 'Aputure LS 600X Pro',             qty: 1 },
  { category: 'Lighting', name: 'Aputure LS 300X BI-Mount',        qty: 1 },
  { category: 'Lighting', name: 'Aputure Accent B7C 8-Light Kit',  qty: 1 },
  { category: 'Lighting', name: 'Arri 2K',                         qty: 2 },
  { category: 'Lighting', name: 'Arri 1K',                         qty: 1 },
  { category: 'Lighting', name: 'Dedo Lights 150w',                qty: 4 },
  { category: 'Lighting', name: 'Zhiyun Molus 100W',               qty: 1 },
  { category: 'Lighting', name: 'Zhiyun Molus G60W',               qty: 1 },
  { category: 'Lighting', name: 'Lite Panels Gemini 1x1',          qty: 1 },

  // ── Modifiers ─────────────────────────────────────────────────────────────
  { category: 'Modifiers', name: 'Aputure F10 Fresnel',                qty: 1 },
  { category: 'Modifiers', name: 'Aputure Light Dome Mini MKII',       qty: 1 },
  { category: 'Modifiers', name: 'Aputure F10 Barn Doors',             qty: 1 },
  { category: 'Modifiers', name: 'Aputure Lantern 90',                 qty: 1 },
  { category: 'Modifiers', name: 'Aputure Spotlight Mount Set 26 Deg', qty: 1 },
  { category: 'Modifiers', name: 'Aputure Lightbox 30120',             qty: 1 },
  { category: 'Modifiers', name: 'SmallRig LA D65',                    qty: 1 },
  { category: 'Modifiers', name: 'Godox S120T',                        qty: 1 },

  // ── Support ───────────────────────────────────────────────────────────────
  { category: 'Support', name: 'Matthews 48x48 Road Flag Kit II',  qty:  1 },
  { category: 'Support', name: 'Fabric Sheets',                    qty:  5 },
  { category: 'Support', name: 'C-Stand Arm',                      qty:  3 },
  { category: 'Support', name: 'Lightstand',                       qty: 10 },
  { category: 'Support', name: 'C-Stand',                          qty:  1 },
  { category: 'Support', name: 'Knuckle',                          qty:  4 },
  { category: 'Support', name: 'Gaff Tape',                        qty:  3 },
  { category: 'Support', name: 'Black Foil',                       qty:  1 },
  { category: 'Support', name: 'Sachtler Aktiv 8 Flowtech',        qty:  2 },
  { category: 'Support', name: 'DJI RS3 Gimbal',                   qty:  1 },
  { category: 'Support', name: 'Sandbag',                          qty: 12 },
  { category: 'Support', name: 'Slider 3m',                        qty:  1 },
  { category: 'Support', name: 'Smallrig Teleprompter',            qty:  1 },
  { category: 'Support', name: 'Tilta Manual Follow Focus',        qty:  2 },
  { category: 'Support', name: 'Tilta Nucleus M Follow Focus',     qty:  1 },
  { category: 'Support', name: 'Pelican 1510 Carry On',            qty:  2 },
  { category: 'Support', name: 'Pelican 1615 Air Case',            qty:  2 },
  { category: 'Support', name: 'Smallrig Magic Arm + Clamp',       qty:  4 },
  { category: 'Support', name: 'Color Checker Passport Photo 2',   qty:  1 },
  { category: 'Support', name: 'Vlock Plate',                      qty:  1 },
  { category: 'Support', name: 'Smallrig Base Plate Rod',          qty:  4 },
  { category: 'Support', name: 'Smallrig Base Plate',              qty:  2 },
  { category: 'Support', name: 'Smallrig Top Handle',              qty:  2 },
  { category: 'Support', name: 'Smallrig Monitor Mount',           qty:  4 },
  { category: 'Support', name: 'Tilta Top Handle',                 qty:  2 },
  { category: 'Support', name: 'Tilta Side Handle',                qty:  2 },
  { category: 'Support', name: 'Smallrig Side Handle',             qty:  3 },
  { category: 'Support', name: 'Lazy Susan',                       qty:  1 },
  { category: 'Support', name: 'Tilta Base Plate Rod',             qty:  4 },

  // ── Batteries ─────────────────────────────────────────────────────────────
  { category: 'Batteries', name: 'Sony Battery',            qty:  8 },
  { category: 'Batteries', name: 'Fujifilm Battery',         qty:  1 },
  { category: 'Batteries', name: 'Insta360 Battery',         qty:  2 },
  { category: 'Batteries', name: 'Osmo Battery',            qty: 12 },
  { category: 'Batteries', name: 'Smallrig Vlock VB99',     qty: 10 },
  { category: 'Batteries', name: 'Neewer Vlock 99Wh',        qty:  1 },
  { category: 'Batteries', name: 'Vlock Battery',            qty:  3 },
  { category: 'Batteries', name: 'Anker PowerCore 10K',      qty:  4 },
  { category: 'Batteries', name: 'Zedamsan 100W Powerbank',  qty:  1 },
  { category: 'Batteries', name: 'Anker 140W Powerbank',     qty:  2 },
  { category: 'Batteries', name: 'Viltrox NPF 4400mAh',      qty:  2 },
  { category: 'Batteries', name: 'Viltrox NPF 2200mAh',      qty:  4 },

  // ── Drone ─────────────────────────────────────────────────────────────────
  { category: 'Drone', name: 'DJI FPV',    qty: 1 },
  { category: 'Drone', name: 'DJI Mini 3', qty: 1 },

  // ── Data ──────────────────────────────────────────────────────────────────
  { category: 'Data', name: 'Lexar SD 64GB',             qty: 1 },
  { category: 'Data', name: 'Lexar SD 128GB',            qty: 4 },
  { category: 'Data', name: 'Lexar CFA 80GB',            qty: 1 },
  { category: 'Data', name: 'Lexar CFA 160GB',           qty: 1 },
  { category: 'Data', name: 'Lexar CFA 320GB',           qty: 1 },
  { category: 'Data', name: 'Sony Tough 160GB',          qty: 1 },
  { category: 'Data', name: 'Angelbird CFB 1TB',         qty: 4 },
  { category: 'Data', name: 'Sandisk SD 32GB',           qty: 1 },
  { category: 'Data', name: 'Sandisk Micro SD 64GB',     qty: 4 },
  { category: 'Data', name: 'Sandisk Micro SD 128GB',    qty: 4 },
  { category: 'Data', name: 'Sandisk Micro SD 256GB',    qty: 4 },
  { category: 'Data', name: 'Samsung Micro SD 128GB',    qty: 4 },
  { category: 'Data', name: 'Samsung Micro SD 512GB',    qty: 2 },
  { category: 'Data', name: 'Insta360 Micro SD 256GB',   qty: 2 },
  { category: 'Data', name: 'Samsung SSD 1TB',           qty: 2 },
  { category: 'Data', name: 'Samsung SSD 500GB',         qty: 1 },
  { category: 'Data', name: 'Sandisk Extreme Pro SSD 4TB', qty: 1 },
  { category: 'Data', name: 'UGreen SSD 4TB',            qty: 1 },
  { category: 'Data', name: 'Lexar CFA Reader',          qty: 2 },
  { category: 'Data', name: 'Lexar CFB Reader',          qty: 2 },
  { category: 'Data', name: 'Lexar SD Card Reader',      qty: 3 },
  { category: 'Data', name: 'Data Kit Pouch',            qty: 1 },

  // ── Power ─────────────────────────────────────────────────────────────────
  { category: 'Power', name: 'Sony Charger',                  qty: 2 },
  { category: 'Power', name: 'Fujifilm Charger',              qty: 1 },
  { category: 'Power', name: 'NPF Charger',                   qty: 2 },
  { category: 'Power', name: 'Sefitopher Fast Charging Brick',qty: 2 },
  { category: 'Power', name: 'UGreen Square Power Brick',     qty: 1 },
];

export const CATEGORIES = [...new Set(DEFAULT_INVENTORY.map(item => item.category))];
