export const DEFAULT_INVENTORY = [
  { id: 1,  category: "Camera",    name: "RED Scarlet W",                  qty: 1 },
  { id: 2,  category: "Camera",    name: "RED Dragon-X",                   qty: 1 },
  { id: 3,  category: "Camera",    name: "Sony A7SIII",                    qty: 1 },
  { id: 4,  category: "Camera",    name: "Panasonic GH5",                  qty: 1 },
  { id: 5,  category: "Camera",    name: "Sony FX3",                       qty: 1 },
  { id: 6,  category: "Camera",    name: "JVC GR-DVL765EG",                qty: 1 },
  { id: 7,  category: "Lenses",    name: "Canon 70-200mm f/2.8 EF",        qty: 1 },
  { id: 8,  category: "Lenses",    name: "Sigma 18-35mm f/1.8 EF",         qty: 2 },
  { id: 9,  category: "Lenses",    name: "Laowa Probe Lens",               qty: 1 },
  { id: 10, category: "Lenses",    name: "Samyang Fisheye",                qty: 1 },
  { id: 11, category: "Lenses",    name: "XEEN 35mm Cinelens Prime",       qty: 1 },
  { id: 12, category: "Lenses",    name: "Sigma 24-70mm f/2.8 E Mount",    qty: 2 },
  { id: 13, category: "Lenses",    name: "Tamron 70-180mm f/2.8 E Mount",  qty: 1 },
  { id: 14, category: "Lenses",    name: "Sigma 30mm f/2.8 MFT",          qty: 1 },
  { id: 15, category: "Lenses",    name: "Panasonic 12-35mm f/2.8 MFT",   qty: 1 },
  { id: 16, category: "Lenses",    name: "Panasonic 14mm f/2.8 MFT",      qty: 1 },
  { id: 17, category: "Adapters",  name: "Metabones EF-E Mount T",         qty: 1 },
  { id: 18, category: "Adapters",  name: "Metabones EF-MFT Mount T",       qty: 1 },
  { id: 19, category: "Adapters",  name: "Sigma MC-11 EF-E",               qty: 1 },
  { id: 20, category: "Filters",   name: "Gobe Variable ND 82mm",          qty: 4 },
  { id: 21, category: "Filters",   name: "PrismFX Kaleidoscope",           qty: 1 },
  { id: 22, category: "Filters",   name: "Tiffen Circular Polarizer 82mm", qty: 1 },
  { id: 23, category: "Filters",   name: "Tiffen Black Pro Mist 82mm",     qty: 4 },
  { id: 24, category: "Action Cam",name: "GoPro Max",                      qty: 3 },
  { id: 25, category: "Action Cam",name: "GoPro Hero 10",                  qty: 2 },
  { id: 26, category: "Action Cam",name: "GoPro Hero 11",                  qty: 1 },
  { id: 27, category: "Action Cam",name: "GoPro Fusion",                   qty: 1 },
  { id: 28, category: "Action Cam",name: "GoPro Hero 6",                   qty: 1 },
  { id: 29, category: "Audio",     name: "Zoom H6 Recorder",               qty: 2 },
  { id: 30, category: "Audio",     name: "Zoom H8 Recorder",               qty: 1 },
  { id: 31, category: "Audio",     name: "Rode NTG-II Shotgun Mic",        qty: 4 },
  { id: 32, category: "Audio",     name: "Sennheiser ew G4 Wireless",      qty: 2 },
  { id: 33, category: "Audio",     name: "Rode Video Mic Pro+",            qty: 2 },
  { id: 34, category: "Audio",     name: "Rode Lavelier II",               qty: 2 },
  { id: 35, category: "Audio",     name: "DJI Mic Set",                    qty: 3 },
  { id: 36, category: "Audio",     name: "Andoer MK-3500 Boom Pole",       qty: 4 },
  { id: 37, category: "Audio",     name: "XLR Cable 6m",                   qty: 4 },
  { id: 38, category: "Audio",     name: "XLR Cable 10m",                  qty: 1 },
  { id: 39, category: "Lighting",  name: "Aputure 1200d",                  qty: 1 },
  { id: 40, category: "Lighting",  name: "Aputure LS 600C Pro II",         qty: 1 },
  { id: 41, category: "Lighting",  name: "Aputure LS 600x Pro",            qty: 1 },
  { id: 42, category: "Lighting",  name: "Aputure LS 300x",                qty: 1 },
  { id: 43, category: "Lighting",  name: "Aputure Accent B7c 8-Light Kit", qty: 1 },
  { id: 44, category: "Lighting",  name: "Arri 2K",                        qty: 2 },
  { id: 45, category: "Lighting",  name: "Arri 1K",                        qty: 1 },
  { id: 46, category: "Lighting",  name: "Dedo Lights 150w",               qty: 4 },
  { id: 47, category: "Lighting",  name: "Zhiyun Molus 100W",              qty: 1 },
  { id: 48, category: "Lighting",  name: "Zhiyun Molus G60W",              qty: 1 },
  { id: 49, category: "Lighting",  name: "Lite Panels Caliber",            qty: 1 },
  { id: 50, category: "Modifiers", name: "Aputure F10 Fresnel",            qty: 1 },
  { id: 51, category: "Modifiers", name: "Aputure F10 Barn Doors",         qty: 1 },
  { id: 52, category: "Modifiers", name: "Aputure Spotlight Mount 26 deg", qty: 1 },
  { id: 53, category: "Modifiers", name: "Aputure Light Dome Mini MKII",   qty: 1 },
  { id: 54, category: "Modifiers", name: "Aputure Lantern 90",             qty: 1 },
  { id: 55, category: "Modifiers", name: "Matthews 48x48 Road Flag Kit",   qty: 1 },
  { id: 56, category: "Monitoring",name: "DJI Transmission Combo",         qty: 1 },
  { id: 57, category: "Monitoring",name: "Atomos Ninja V",                 qty: 1 },
  { id: 58, category: "Monitoring",name: "Atomos Shinobi 7",               qty: 1 },
  { id: 59, category: "Monitoring",name: "CVW HDMI Wireless Monitor Kit",  qty: 1 },
  { id: 60, category: "Drones",    name: "DJI Phantom 4 Pro+",             qty: 1 },
  { id: 61, category: "Drones",    name: "DJI FPV",                        qty: 1 },
  { id: 62, category: "Drones",    name: "DJI Mini 3",                     qty: 1 },
  { id: 63, category: "Drones",    name: "BIGBY Watermelon FPV",           qty: 1 },
  { id: 64, category: "Support",   name: "Manfrotto 504HD Tripod",         qty: 2 },
  { id: 65, category: "Support",   name: "Manfrotto 190x Tripod",          qty: 1 },
  { id: 66, category: "Support",   name: "DJI Ronin RS2 Gimbal",           qty: 1 },
  { id: 67, category: "Support",   name: "Digidolly 3m Slider Kit",        qty: 1 },
  { id: 68, category: "Support",   name: "C-Stand",                        qty: 1 },
  { id: 69, category: "Support",   name: "C-Stand Arm",                    qty: 3 },
  { id: 70, category: "Support",   name: "Arri Lighting Stands",           qty: 14 },
  { id: 71, category: "Support",   name: "Neewer Large Light Stand",       qty: 4 },
  { id: 72, category: "Support",   name: "Bowens Medium Stand",            qty: 2 },
  { id: 73, category: "Support",   name: "Bowens Small Stand",             qty: 2 },
  { id: 74, category: "Support",   name: "Teleprompter",                   qty: 1 },
];

export const CATEGORIES = [...new Set(DEFAULT_INVENTORY.map(item => item.category))];
